# Generated by Django 3.2.18 on 2023-04-06 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='food_review',
            field=models.CharField(blank=True, choices=[('delicious', 'Delicious'), ('not_salty_enough', 'Not Salty Enough'), ('too_sweet', 'Too Sweet'), ('not_so_good', 'Not So Good')], max_length=32),
        ),
        migrations.AddField(
            model_name='post',
            name='review_grade',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('F', 'F')], max_length=2),
        ),
    ]
