# Generated by Django 3.2.4 on 2023-03-21 15:06

from django.db import migrations, models
import django.db.models.deletion
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ForeignKey(default=posts.models.get_default_category, on_delete=django.db.models.deletion.CASCADE, to='categories.category'),
        ),
    ]
