# Generated by Django 3.2.18 on 2023-03-17 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='uuid',
        ),
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='../default_profile_bhadqa', upload_to='images/'),
        ),
    ]
