# Generated by Django 3.2.4 on 2023-03-27 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0002_rename_likes_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='content',
        ),
        migrations.RemoveField(
            model_name='like',
            name='updated_at',
        ),
    ]
