# Generated by Django 3.2.4 on 2023-03-27 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0003_auto_20230327_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='content',
            field=models.TextField(default='Default content'),
        ),
        migrations.AddField(
            model_name='like',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
