# Generated by Django 3.2.4 on 2023-03-27 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0004_auto_20230327_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='content',
            field=models.TextField(),
        ),
    ]
