# Generated by Django 3.2.4 on 2023-03-27 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0005_alter_like_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='content',
        ),
        migrations.RemoveField(
            model_name='like',
            name='updated_at',
        ),
    ]
